### ISSUE TITLE
Add author affiliation to upload page and meta.yaml

### ISSUE THREAD

**Issue by wd15** [usnistgov/pfhub#1138]
Back fill existing meta.yaml where possible and add to upload form

**Comment by tkphd** [comment]
I am opposed to this change. Do we have a need for this data? Is it worth the extra field? Does a person need to be affiliated with an institution to use phase-field tools or upload a valid result?

I think the answer is "no" to all the above.

**Comment by wd15** [comment]
The MDF team would like it as it's part of their schema for indexable data. It doesn't have to be mandatory.

**Comment by stvdwtt** [comment]
While I agree with @tkphd in principle that someone doesn't need to be affiliated with an institution to post to PFHub, practically speaking most, if not all, will. Adding an optimal field doesn't seem too onerous. I could also see it being beneficial to track affiliations just so that we can tout that we have A uploads from B users at C institutions in D countries.

That said, I don't think there would be a reason to display institutional affiliation prominently anywhere associated with the uploads.

[Also, hello again! I'm glad to hear that the last meeting went well and I look forward to seeing everyone in April.]

**Comment by tkphd** [comment]
Perhaps we could infer the affiliation from the e-mail address, with an optional field that would be used *e.g.* for gmail?
