### ISSUE TITLE
Finish spec for problem 7

### ISSUE THREAD

**Issue by wd15** [usnistgov/pfhub#519]

**Comment by wd15** [comment]
@stvdwtt, do you want to add this to the website in a notebook (or do you want me to do that)?

**Comment by stvdwtt** [comment]
@wd15 I'll take care of it, my plan is to have a draft ready by the end of next week. I still have to double-check the parameters and run the final problem statement by the organizers.

**Comment by wd15** [comment]
The notebook: https://github.com/stvdwtt/chimad-phase-field/blob/benchmark7/benchmarks/benchmark7.ipynb

**Comment by wd15** [comment]
@stvdwtt: shall I go ahead and add the notebook as problem7?

**Comment by tkphd** [comment]
@stvdwtt, if you approve of the revisions, please merge [my pull request](https://github.com/stvdwtt/chimad-phase-field/pull/4) before @wd15 adds `benchmark7.ipynb` to the website.

**Comment by stvdwtt** [comment]
@wd15 @tkphd The one thing I'm unsure about is what to do with the upload instructions. I know at the last meeting we pushed the problem 7 upload form to a stretch goal, but now that the upload form can handle an arbitrary number of datasets, it should be straightforward to do that, right?

@wd15 I know you have a lot on your plate to get the site ready, would it require much work on your end to allow benchmark 7 uploads? For now, I think it'd be fine to skip plots and landing pages and the like if that's time-consuming, since we could build that out later. I think people being able to upload their data as they work on the problem would be a big plus.

**Comment by wd15** [comment]
Firstly, don't worry too much about the upload instructions, yet. Just include what you think might work. For milestone [v0.4.3](https://github.com/usnistgov/pfhub/milestone/11), I'm going to try and get all the simulation result comparison landing pages up, including, problem 7 if you can give me data. In that process we can refine the instructions for the upload and also the other problems.

Secondly, yes, I think the upload form will probably handle arbitrary data so problem 7 will work. Anyway, we'll see won't we and fix it so that it works during milestone [v0.4.3](https://github.com/usnistgov/pfhub/milestone/11),

Thirdly, the landing page for each individual simulation result won't be any different for problem 7, but the comparison landing page will require some work, especially refining the comparison plots to be what we want to see. Again this can get done as part of [v0.4.3](https://github.com/usnistgov/pfhub/milestone/11).

**Comment by wd15** [comment]
So, right now you should just try and get the spec up without worrying too much about refining the upload instructions.

**Comment by stvdwtt** [comment]
Sounds good, I'll get to work on it today.

**Comment by tkphd** [comment]
*N.B.* @wd15, @stvdwtt merged my [PR](https://github.com/stvdwtt/chimad-phase-field/pull/4) into `master`, not the  `benchmark7` branch. Please consider this when merging into the `usnistgov` repo.
