### ISSUE TITLE
MMS benchmark analysis

### ISSUE THREAD

**Issue by tkphd** [usnistgov/pfhub#738]
I believe that determining the spatial order of accuracy requires a log-log plot of $l_2$ vs. $1/h$, then extracting the exponent of the power-law fit.

References:
- [MASA](https://github.com/manufactured-solutions/presentations/blob/master/CPSSW_2017_workshop/rawfigs/laplace_central_diff1.pdf) for finite differencing: should produce m=-2.
- [COMSOL](https://www.comsol.com/blogs/verify-simulations-with-the-method-of-manufactured-solutions/) for finite elements: should produce m=-3, or whatever order of element you choose:
![comsol-mms](https://user-images.githubusercontent.com/2179347/36121608-b9f908f4-1014-11e8-95dc-821029f6bcfd.png)

**Comment by tkphd** [comment]
So, the PRISMS_QUAD shows accuracy $O(x^1.94)$ based on the available data. Adding more mesh refinements should tighten this estimate, hopefully closer to 2.

![prisms-mms](https://user-images.githubusercontent.com/2179347/36121069-2243cbe4-1013-11e8-8b86-3431919e9d7b.png)

**Comment by tkphd** [comment]
Just to make this issue actionable, I am requesting that @stvdwtt update the Benchmark 7 notebook to request simulation data as a CSV or JSON file containing two columns or keys: inverse-h and L2-norm, or log(1/h) and log(L2-norm), and requiring that the figure caption contain the slope of the power law fit. 

@wd15, can plotly (is that our back-end?) plot lines of best fit?

**Comment by wd15** [comment]
@tkphd, I'm shifting from Vega to Plotly at the moment. Plotly probably does do best fit, but there are plenty of JS libraries to do basic maths so no worries with that.

**Comment by tkphd** [comment]
OK, sounds like we can transform inputs and extract the equation online. Neat!

**Comment by stvdwtt** [comment]
I was hoping that we'd be able to automatically extract the order of accuracy, but I figured that was something to add down the line. I'm glad to hear that (eventually) it should be relatively straightforward.

@tkphd You don't actually need to do 1/h -- you can do the exponential fit on h and the L2 error. All that changes is the sign (i.e. for 1/h the fit for second order accuracy is -2, for h it is +2).

Regarding the spatial accuracy of the PRISMS-PF run, I have no idea why it is higher than anticipated. The peak slope of that plot is over 4 and is dragged down by not resolving the interface for large h and temporal discretization error for small h. That was something I was planning to bring up at the meeting. The simulation with linear elements is pretty much dead-on 2, as expected. (Those results I haven't uploaded yet, but will soon.)

Just for confirmation, since we can (eventually) do processing on the backend, the as-written text is ok?

If we have the capability for backend processing, it'd be great if we could calculate the effective computational cost for the user. Currently, the text asks the contributor to:

> save the wall time (in seconds), number of computing cores, normalized computing cost (wall time in seconds × number of cores × nominal core speed /2 GHz), maximum memory usage, and L2L2 error at t=8t=8 for each individual simulation in a CSV or JSON file.

**Comment by stvdwtt** [comment]
> While you can do the exponential fit on L2 vs h, the canonical MMS analysis is to fit a line on the log-log plot. This makes the multi-decade span of L2 and h easier to visualize, and people are better at seeing deviations from a line than deviations from exp. Also, for enterprising benchmarkers who want to read more, having data in the canonical form will make it easier to reconcile against the MMS literature.

I think we're on the same page. Log-log plots are definitely the way to go for visualization purposes. My point was only that you can do it with h rather than 1/h (and I think h is more natural).

>My gut tells me there aren't enough points for low h to overcome the point at high h, so doing more refinements should help; or, choosing a smaller h0 to begin with. If you have data to the contrary, it'll be interesting to discuss at the workshop.

I haven't dug into it too deep yet, let's follow-up at the workshop.

>I think it's valuable for benchmarkers to be able to see their analyzed result before uploading it. That's one reason we have people calculate F vs t for the earlier problems: it's a good spot-check. I would prefer to revise the procedure to walk through the analysis, then request just the CSV or JSON of h and L2 for upload.

I agree. Unless I'm misunderstanding you, we already ask the contributed to calculate the order of accuracy themselves for that very reason. Or am I missing something?

>There's not a strong reason for breaking this out into "individual simulations": main can contain a loop over h, printing one line per step; or the user can aggregate output from a simpler main before upload. Either way, there should be just one wall time and one memory usage.

Let's discuss this at the workshop. I feel like breaking it into individual simulations is more natural and is likely to yield more interesting information.

> Computational cost is too specific, and beside the point for MMS. My feeling is that modern CPUs should be considered interchangeable, and the short runtime of the MMS codes is an adequate proxy for its low computational cost. Again, if you have feelings or data to the contrary, it'll make a good topic for workshop discussion.

Yes, let's discuss this at the workshop. Aside from testing, I think there's promise in using MMS for performance benchmarking.

**Comment by tkphd** [comment]
Great. I'm working through the benchmark, and will have better feedback after actually following the directions :smiley:

**Comment by stvdwtt** [comment]
Great!

**Comment by tkphd** [comment]
Closing, since there's nothing actionable here. OK, @stvdwtt?
