### ISSUE TITLE
Investigage why Chrome does not load figshare data

### ISSUE THREAD

**Issue by wd15** [usnistgov/pfhub#751]
This is an issue with the 3a comparison page. This may be due to dl.load being call synchronously in my code. In Vega, it's probably loaded asynchronously. See, https://github.com/vega/datalib/wiki/Import.

This doesn't explain why data from a Gist still works fine, but data from Figshare doesn't work.

**Comment by wd15** [comment]
Figshare data load on individual display page for e87db22b34fe

http://127.0.0.1:4000/pfhub/simulations/display/?sim=fipy_3a

but not on 

http://127.0.0.1:4000/pfhub/simulations/3a.1/

for Figshare data. Is that to do with async versus sync? The plots on the individual pages are plotted using Vega, which is internally using dl.load, but with an async design, while I'm using Plotly is an sync manner and there isn't an easy way to do it with an async callback. I need to look more at the Plotly docs on this.

**Comment by wd15** [comment]
So, using plotly, we can specify empty "traces" in the data section and then update those traces asynchronously using, https://plot.ly/javascript/plotlyjs-function-reference/#plotlyextendtraces. I think this will work. So every "dl.load" will load the data and call an asyncrnous call back that updates the plot, which has already been generated with empty data.

**Comment by tkphd** [comment]
Is this still an issue?

**Comment by wd15** [comment]
Data for "hiperc_1b_cuda_9pt" loads now on the comparison page. The reason why it doesn't load on the individual page is because the loading is synchronous on those pages and needs to be made asynchronous as it is on the individual pages. However, this issue is nothing to do with Figshare. It is a bug for all data in chrome. New issue for this #1067

**Comment by eduardofox2** [comment]
I have also just failed to load RData from Figshare, and thus will stick with github instead...

**Comment by tkphd** [comment]
Hi @eduardofox2, 

Without context, it's hard to know what's going on in your case. Note that in this issue, the problem was on "our" end (how pfhub was loading data), not a problem with Figshare. GitHub is not a long-term solution for accessible, searchable, reusable data archives, since Git and GitHub by extension are meant to track changes in text-based source code. If you would like to discuss alternatives, or perhaps troubleshoot your application's difficulty with Figshare-hosted data, please reach out to me at trevor.keller@nist.gov
